import streamlit as st
st.header('UTTARAKHAND')
st.link_button('GRAPHIC ERA HILL UNIVERSITY,BHIMTAL','https://bhimtal.gehu.ac.in/')
st.link_button('GRAPHIC ERA HILL UNIVERSITY-DEHRADUN','https://dehradun.gehu.ac.in/')
st.link_button('GRAPHIC ERA UNIVERSITY-DEHRADUN','https://geu.ac.in/')
st.link_button('IIT RooRKEE','https://www.iitr.ac.in/')
st.link_button('UPES','https://www.upes.ac.in/')
st.header('UTTARPRADESH')
st.link_button('BANARAS HINDU UNIVERSITY','https://www.bhu.ac.in/Site/Home/1_2_16_Main-Site')
st.link_button('AMITY UNIVERSITY','https://www.amity.edu/')
st.link_button('ALLAHBAD UNIVERSITY','https://www.allduniv.ac.in/')
st.link_button('BAREILLY INTERNATION UNIVERSITY','https://www.biu.edu.in/')
st.header('PUNJAB')
st.link_button('LOVELY PROFESSIONAL  UNIVERSITY','https://www.lpu.in/')
st.link_button('DR B R AMBADKAR UNIVERSITY','https://dbrau.ac.in/')
st.link_button('CHITKARA UNIVERSITY','https://www.chitkara.edu.in/')
st.link_button(' THAPAR INSTITUTE OF ENGINEERING','https://www.thapar.edu/')
st.header('KERALA')
st.link_button('UNIVERSITY OF KERALA','https://www.keralauniversity.ac.in/')
st.link_button('UNIVERSITY OF CALICUT','https://uoc.ac.in/')
st.link_button('KANNUR UNIVERSITY','https://www.kannuruniversity.ac.in/en/')
st.link_button('COCHIN UNIVERSITY OF SCIENCE','https://cusat.ac.in/')